input:
  train:
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/bb/merge_bb_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/cc/merge_cc_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/gg/merge_gg_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/bbbar/merge_bbbar_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/ccbar/merge_ccbar_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/dd/merge_dd_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/ddbar/merge_ddbar_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/uu/merge_uu_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/uubar/merge_uubar_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/ss/merge_ss_*.root" ]
    - [ "/cefs/higgs/zhuyifan/sample/training/input/input/merge/ssbar/merge_ssbar_*.root" ]
  val: ["/cefs/higgs/zhuyifan/sample/training/input/input/merge/val/*"]
  test: ["/cefs/higgs/zhuyifan/sample/training/input/input/merge/test/*"]

#---root -> csv

tree_name: "tree"
start_entry: null
end_entry: null
cut: null
#

#---training

features:
  - jet_eta
  - jet_energy
  - jet_pt
  - jet_phi
  - jet_nparticles
  - btag
  - ctag
  - part_dphi_0
  - part_dphi_1
  - part_dphi_2
  - part_dphi_3
  - part_dphi_4
  - part_deta_0
  - part_deta_1
  - part_deta_2
  - part_deta_3
  - part_deta_4
  - part_pt_log_0
  - part_pt_log_1
  - part_pt_log_2
  - part_pt_log_3
  - part_pt_log_4

observables:
  - jet_eta
  - jet_energy
  - event_number

labels:
  - label_b
  - label_bbar
  - label_c
  - label_cbar
  - label_u
  - label_ubar
  - label_d
  - label_dbar
  - label_s
  - label_sbar
  - label_g


target: bdtlabel

xgboost_params:
  objective: multi:softprob
  num_class: 11
  max_depth: 6
  eta: 0.1
#  eval_metric: mlogloss