input:
  train:
    - [ "/your path/merge/bb/merge_bb_*.root" ]
    - [ "/your path/merge/cc/merge_cc_*.root" ]
    - [ "/your path/gg/merge_gg_*.root" ]
    - [ "/your path/bbbar/merge_bbbar_*.root" ]
    - [ "/your path/merge/ccbar/merge_ccbar_*.root" ]
    - [ "/your path/merge/dd/merge_dd_*.root" ]
    - [ "/your pathmerge/ddbar/merge_ddbar_*.root" ]
    - [ "/your path/merge/uu/merge_uu_*.root" ]
    - [ "/your path/merge/uubar/merge_uubar_*.root" ]
    - [ "/your path/merge/ss/merge_ss_*.root" ]
    - [ "/your path/merge/ssbar/merge_ssbar_*.root" ]
  val: ["/your path/merge/val/*"]
  test: ["/your path/merge/test/*"]

#---root -> csv

tree_name: "tree"
start_entry: null
end_entry: null
cut: null
#

#---training

features:
  - jet_eta
  - jet_energy
  - jet_pt
  - jet_phi
  - jet_nparticles

observables:
  - jet_eta
  - jet_energy
  - event_number

labels:
  - label_b
  - label_bbar
  - label_c
  - label_cbar
  - label_u
  - label_ubar
  - label_d
  - label_dbar
  - label_s
  - label_sbar
  - label_g

target: bdtlabel

xgboost_params:
  objective: multi:softprob
  num_class: 11
  max_depth: 6
  eta: 0.1
  eval_metric: mlogloss